### ISSUE TITLE
Bot Not Responding

### ISSUE THREAD

**Issue by LordofdaHell** [artxia/IBM-gd-utils#33]
This is the format in which I put the Secrets - 

TG_USERNAME - myusername (without '@')
TG_TOKEN - 1353362376:AAGwaLhskIJSrKOiBghksjsgs6HHAEKsqau8zk
IBM_APP_NAME - myappname
IBM_PWD - ibmpassword
IBM_MAIL - myemail@gmail.com
SA_DLURL - https://docs.google.com/uc?export=download&id=10bT_1160Af9sslkn826GS98
DRIVE_ID - 7Vx8kOIhls6KlraX7a9hjaaiB5hsoMtgjC

I did Auto install and it says successful but bot is not responding.I tried creating another boy but it still is not responding.I don't know what I am doing wrong.Can anyone help me ?

**Comment by artxia** [comment]
https://github.com/artxia/IBM-gd-utils/issues/4

If there is a "500" error after installation, the reason is that the container address is not correct, you need to log in to IBM to find the container settings manually changed to "us-south.cf.appdomain.cloud", and then check whether the container name in front and your settings "IBM_APP_NAME" are consistent, change it and re-operation step 4

![image](https://user-images.githubusercontent.com/50513568/102684302-40446200-4212-11eb-9238-8f082e0cbbad.png)

**Comment by LordofdaHell** [comment]
So I changed the settings to "us-south.cf.appdomain.cloud", then reinstall it."gd-utils-active-impala-tq" this is what the route in the container settings looks like and the value of "IBM_APP_NAME" is "GD-Util". Actually I didn't understand what do you mean by consistent.You mean both "gd-utils-active-impala-tq" and Value of my secret "IBM_APP_NAME" should be same ? After re-installation nothing is changed and bot is still not working.

**Comment by artxia** [comment]
Yes, "gd-utils-active-impala-tq" and your secret "IBM_APP_NAME" should be the same.

**Comment by LordofdaHell** [comment]
Thanks.Now I understand the whole thing and it worked.Just a last question, there is too much of Chinese language that I don't understand so is there any option for English ? Just asking

**Comment by artxia** [comment]
> Thanks.Now I understand the whole thing and it worked.Just a last question, there is too much of Chinese language that I don't understand so is there any option for English ? Just asking

https://github.com/artxia/IBM-gd-utils#English-Version
